// Code generated by viemgen. DO NOT EDIT.
package univ2factory

import (
	"context"
	"math/big"
	"sync"

	"github.com/ChefBingbong/viem-go/abi"
	"github.com/ChefBingbong/viem-go/client"
	"github.com/ChefBingbong/viem-go/contract"
	"github.com/ChefBingbong/viem-go/types"
	"github.com/ethereum/go-ethereum/common"
)

// Suppress unused import warnings
var (
	_ = big.NewInt
	_ = common.Address{}
	_ types.Transaction
	_ sync.Once
	_ *abi.ABI
)

// ContractABI is the raw JSON ABI of the UniV2Factory contract.
var ContractABI = `[
  {
    "inputs": [],
    "name": "allPairsLength",
    "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "name": "allPairs",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  }
]
`

// parsedABI holds the parsed ABI (lazily initialized).
var (
	parsedABI     *abi.ABI
	parsedABIOnce sync.Once
	parsedABIErr  error
)

// ParsedABI returns the pre-parsed ABI for the UniV2Factory contract.
// This is useful for efficient multicall operations where you want to avoid
// re-parsing the ABI JSON on every call.
// The ABI is parsed once and cached for subsequent calls.
func ParsedABI() (*abi.ABI, error) {
	parsedABIOnce.Do(func() {
		parsedABI, parsedABIErr = abi.Parse([]byte(ContractABI))
	})
	return parsedABI, parsedABIErr
}

// MustParsedABI returns the pre-parsed ABI, panicking on error.
// Use this when you're confident the ABI is valid (e.g., in init or tests).
func MustParsedABI() *abi.ABI {
	parsed, err := ParsedABI()
	if err != nil {
		panic("failed to parse UniV2Factory ABI: " + err.Error())
	}
	return parsed
}

// ============================================================================
// Typed Method Descriptors
// ============================================================================

// UniV2FactoryMethods defines typed method descriptors for the UniV2Factory contract.
// Use these with contract.ReadTyped() for type-safe calls.
type UniV2FactoryMethods struct {
	AllPairsLength contract.ReadBigInt
	AllPairs       contract.ReadAddress
}

// Methods is the typed method descriptors instance for UniV2Factory.
// Use with contract.ReadTyped(c.Contract(), ctx, Methods.MethodName, args...)
var Methods = UniV2FactoryMethods{
	AllPairsLength: contract.ReadBigInt{Name: "allPairsLength"},
	AllPairs:       contract.ReadAddress{Name: "allPairs"},
}

// ============================================================================
// Contract Binding
// ============================================================================

// UniV2Factory is a binding to the UniV2Factory contract.
type UniV2Factory struct {
	contract *contract.Contract
	M        UniV2FactoryMethods // Typed method descriptors
}

// New creates a new UniV2Factory contract binding.
func New(address common.Address, c *client.PublicClient) (*UniV2Factory, error) {
	cont, err := contract.NewContract(address, []byte(ContractABI), c)
	if err != nil {
		return nil, err
	}
	return &UniV2Factory{contract: cont, M: Methods}, nil
}

// MustNew creates a new UniV2Factory contract binding, panicking on error.
func MustNew(address common.Address, c *client.PublicClient) *UniV2Factory {
	cont, err := New(address, c)
	if err != nil {
		panic(err)
	}
	return cont
}

// Address returns the contract address.
func (c *UniV2Factory) Address() common.Address {
	return c.contract.Address()
}

// Contract returns the underlying contract instance.
func (c *UniV2Factory) Contract() *contract.Contract {
	return c.contract
}

// ABI returns the raw JSON ABI string.
func (c *UniV2Factory) ABI() string {
	return ContractABI
}

// ABIBytes returns the raw JSON ABI as bytes.
// This is the format expected by multicall and other ABI-consuming functions.
func (c *UniV2Factory) ABIBytes() []byte {
	return []byte(ContractABI)
}

// ParsedABI returns the pre-parsed ABI for efficient reuse.
// Useful for multicall operations to avoid re-parsing the ABI.
func (c *UniV2Factory) ParsedABI() (*abi.ABI, error) {
	return ParsedABI()
}

// AllPairsLength calls the allPairsLength function.
// Solidity: allPairsLength()
func (c *UniV2Factory) AllPairsLength(ctx context.Context) (*big.Int, error) {
	result, err := c.contract.Read(ctx, "allPairsLength")
	if err != nil {
		return nil, err
	}

	return result[0].(*big.Int), nil

}

// AllPairs calls the allPairs function.
// Solidity: allPairs(uint256)
func (c *UniV2Factory) AllPairs(ctx context.Context, arg0 *big.Int) (common.Address, error) {
	result, err := c.contract.Read(ctx, "allPairs", arg0)
	if err != nil {
		return common.Address{}, err
	}

	return result[0].(common.Address), nil

}
