// Code generated by viemgen. DO NOT EDIT.
package erc20bytes32

import (
	"context"
	"math/big"
	"sync"

	"github.com/ChefBingbong/viem-go/abi"
	"github.com/ChefBingbong/viem-go/client"
	"github.com/ChefBingbong/viem-go/contract"
	"github.com/ChefBingbong/viem-go/types"
	"github.com/ethereum/go-ethereum/common"
)

// Suppress unused import warnings
var (
	_ = big.NewInt
	_ = common.Address{}
	_ types.Transaction
	_ sync.Once
	_ *abi.ABI
)

// ContractABI is the raw JSON ABI of the ERC20Bytes32 contract.
var ContractABI = `[
  {
    "type": "function",
    "name": "decimals",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint8" }]
  },
  {
    "type": "function",
    "name": "name",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bytes32" }]
  },
  {
    "type": "function",
    "name": "symbol",
    "stateMutability": "view",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bytes32" }]
  }
]
`

// parsedABI holds the parsed ABI (lazily initialized).
var (
	parsedABI     *abi.ABI
	parsedABIOnce sync.Once
	parsedABIErr  error
)

// ParsedABI returns the pre-parsed ABI for the ERC20Bytes32 contract.
// This is useful for efficient multicall operations where you want to avoid
// re-parsing the ABI JSON on every call.
// The ABI is parsed once and cached for subsequent calls.
func ParsedABI() (*abi.ABI, error) {
	parsedABIOnce.Do(func() {
		parsedABI, parsedABIErr = abi.Parse([]byte(ContractABI))
	})
	return parsedABI, parsedABIErr
}

// MustParsedABI returns the pre-parsed ABI, panicking on error.
// Use this when you're confident the ABI is valid (e.g., in init or tests).
func MustParsedABI() *abi.ABI {
	parsed, err := ParsedABI()
	if err != nil {
		panic("failed to parse ERC20Bytes32 ABI: " + err.Error())
	}
	return parsed
}

// ============================================================================
// Typed Method Descriptors
// ============================================================================

// ERC20Bytes32Methods defines typed method descriptors for the ERC20Bytes32 contract.
// Use these with contract.ReadTyped() for type-safe calls.
type ERC20Bytes32Methods struct {
	Symbol   contract.ReadMethod[[32]byte]
	Decimals contract.ReadUint8
	Name     contract.ReadMethod[[32]byte]
}

// Methods is the typed method descriptors instance for ERC20Bytes32.
// Use with contract.ReadTyped(c.Contract(), ctx, Methods.MethodName, args...)
var Methods = ERC20Bytes32Methods{
	Symbol:   contract.ReadMethod[[32]byte]{Name: "symbol"},
	Decimals: contract.ReadUint8{Name: "decimals"},
	Name:     contract.ReadMethod[[32]byte]{Name: "name"},
}

// ============================================================================
// Contract Binding
// ============================================================================

// ERC20Bytes32 is a binding to the ERC20Bytes32 contract.
type ERC20Bytes32 struct {
	contract *contract.Contract
	M        ERC20Bytes32Methods // Typed method descriptors
}

// New creates a new ERC20Bytes32 contract binding.
func New(address common.Address, c *client.PublicClient) (*ERC20Bytes32, error) {
	cont, err := contract.NewContract(address, []byte(ContractABI), c)
	if err != nil {
		return nil, err
	}
	return &ERC20Bytes32{contract: cont, M: Methods}, nil
}

// MustNew creates a new ERC20Bytes32 contract binding, panicking on error.
func MustNew(address common.Address, c *client.PublicClient) *ERC20Bytes32 {
	cont, err := New(address, c)
	if err != nil {
		panic(err)
	}
	return cont
}

// Address returns the contract address.
func (c *ERC20Bytes32) Address() common.Address {
	return c.contract.Address()
}

// Contract returns the underlying contract instance.
func (c *ERC20Bytes32) Contract() *contract.Contract {
	return c.contract
}

// ABI returns the raw JSON ABI string.
func (c *ERC20Bytes32) ABI() string {
	return ContractABI
}

// ABIBytes returns the raw JSON ABI as bytes.
// This is the format expected by multicall and other ABI-consuming functions.
func (c *ERC20Bytes32) ABIBytes() []byte {
	return []byte(ContractABI)
}

// ParsedABI returns the pre-parsed ABI for efficient reuse.
// Useful for multicall operations to avoid re-parsing the ABI.
func (c *ERC20Bytes32) ParsedABI() (*abi.ABI, error) {
	return ParsedABI()
}

// Symbol calls the symbol function.
// Solidity: symbol()
func (c *ERC20Bytes32) Symbol(ctx context.Context) ([32]byte, error) {
	result, err := c.contract.Read(ctx, "symbol")
	if err != nil {
		return [32]byte{}, err
	}

	return result[0].([32]byte), nil

}

// Decimals calls the decimals function.
// Solidity: decimals()
func (c *ERC20Bytes32) Decimals(ctx context.Context) (uint8, error) {
	result, err := c.contract.Read(ctx, "decimals")
	if err != nil {
		return 0, err
	}

	return result[0].(uint8), nil

}

// Name calls the name function.
// Solidity: name()
func (c *ERC20Bytes32) Name(ctx context.Context) ([32]byte, error) {
	result, err := c.contract.Read(ctx, "name")
	if err != nil {
		return [32]byte{}, err
	}

	return result[0].([32]byte), nil

}
