// Code generated by viemgen (manually patched for multi-return getReserves). DO NOT EDIT.
package univ2pair

import (
	"context"
	"math/big"
	"sync"

	"github.com/ChefBingbong/viem-go/abi"
	"github.com/ChefBingbong/viem-go/client"
	"github.com/ChefBingbong/viem-go/contract"
	"github.com/ChefBingbong/viem-go/types"
	"github.com/ethereum/go-ethereum/common"
)

// Suppress unused import warnings
var (
	_ = big.NewInt
	_ = common.Address{}
	_ types.Transaction
	_ sync.Once
	_ *abi.ABI
)

// ContractABI is the raw JSON ABI of the UniV2Pair contract.
var ContractABI = `[{"constant":true,"inputs":[],"name":"factory","outputs":[{"internalType":"address","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"getReserves","outputs":[{"internalType":"uint112","name":"reserve0","type":"uint112"},{"internalType":"uint112","name":"reserve1","type":"uint112"},{"internalType":"uint32","name":"blockTimestampLast","type":"uint32"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"token0","outputs":[{"internalType":"address","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"token1","outputs":[{"internalType":"address","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint112","name":"reserve0","type":"uint112"},{"indexed":false,"internalType":"uint112","name":"reserve1","type":"uint112"}],"name":"Sync","type":"event"}]`

// parsedABI holds the parsed ABI (lazily initialized).
var (
	parsedABI     *abi.ABI
	parsedABIOnce sync.Once
	parsedABIErr  error
)

// ParsedABI returns the pre-parsed ABI for the UniV2Pair contract.
func ParsedABI() (*abi.ABI, error) {
	parsedABIOnce.Do(func() {
		parsedABI, parsedABIErr = abi.Parse([]byte(ContractABI))
	})
	return parsedABI, parsedABIErr
}

// MustParsedABI returns the pre-parsed ABI, panicking on error.
func MustParsedABI() *abi.ABI {
	parsed, err := ParsedABI()
	if err != nil {
		panic("failed to parse UniV2Pair ABI: " + err.Error())
	}
	return parsed
}

// ============================================================================
// Typed Method Descriptors
// ============================================================================

// UniV2PairMethods defines typed method descriptors for the UniV2Pair contract.
type UniV2PairMethods struct {
	Factory     contract.ReadAddress
	Token0      contract.ReadAddress
	Token1      contract.ReadAddress
	GetReserves contract.ReadMethod[[]any]
}

// Methods is the typed method descriptors instance for UniV2Pair.
var Methods = UniV2PairMethods{
	Factory:     contract.ReadAddress{Name: "factory"},
	Token0:      contract.ReadAddress{Name: "token0"},
	Token1:      contract.ReadAddress{Name: "token1"},
	GetReserves: contract.ReadMethod[[]any]{Name: "getReserves"},
}

// ============================================================================
// Contract Binding
// ============================================================================

// UniV2Pair is a binding to the UniV2Pair contract.
type UniV2Pair struct {
	contract *contract.Contract
	M        UniV2PairMethods // Typed method descriptors
}

// New creates a new UniV2Pair contract binding.
func New(address common.Address, c *client.PublicClient) (*UniV2Pair, error) {
	cont, err := contract.NewContract(address, []byte(ContractABI), c)
	if err != nil {
		return nil, err
	}
	return &UniV2Pair{contract: cont, M: Methods}, nil
}

// MustNew creates a new UniV2Pair contract binding, panicking on error.
func MustNew(address common.Address, c *client.PublicClient) *UniV2Pair {
	cont, err := New(address, c)
	if err != nil {
		panic(err)
	}
	return cont
}

// Address returns the contract address.
func (c *UniV2Pair) Address() common.Address {
	return c.contract.Address()
}

// Contract returns the underlying contract instance.
func (c *UniV2Pair) Contract() *contract.Contract {
	return c.contract
}

// ABI returns the raw JSON ABI string.
func (c *UniV2Pair) ABI() string {
	return ContractABI
}

// ABIBytes returns the raw JSON ABI as bytes.
func (c *UniV2Pair) ABIBytes() []byte {
	return []byte(ContractABI)
}

// ParsedABI returns the pre-parsed ABI for efficient reuse.
func (c *UniV2Pair) ParsedABI() (*abi.ABI, error) {
	return ParsedABI()
}

// Factory calls the factory function.
func (c *UniV2Pair) Factory(ctx context.Context) (common.Address, error) {
	result, err := c.contract.Read(ctx, "factory")
	if err != nil {
		return common.Address{}, err
	}
	return result[0].(common.Address), nil
}

// Token0 calls the token0 function.
func (c *UniV2Pair) Token0(ctx context.Context) (common.Address, error) {
	result, err := c.contract.Read(ctx, "token0")
	if err != nil {
		return common.Address{}, err
	}
	return result[0].(common.Address), nil
}

// Token1 calls the token1 function.
func (c *UniV2Pair) Token1(ctx context.Context) (common.Address, error) {
	result, err := c.contract.Read(ctx, "token1")
	if err != nil {
		return common.Address{}, err
	}
	return result[0].(common.Address), nil
}

// Reserves holds the result of getReserves.
type Reserves struct {
	Reserve0           *big.Int
	Reserve1           *big.Int
	BlockTimestampLast uint32
}

// GetReserves calls the getReserves function.
func (c *UniV2Pair) GetReserves(ctx context.Context) (*Reserves, error) {
	result, err := c.contract.Read(ctx, "getReserves")
	if err != nil {
		return nil, err
	}
	return &Reserves{
		Reserve0:           result[0].(*big.Int),
		Reserve1:           result[1].(*big.Int),
		BlockTimestampLast: uint32(result[2].(*big.Int).Uint64()),
	}, nil
}

// Event types

// SyncEvent represents a Sync event.
type SyncEvent struct {
	Reserve0 *big.Int
	Reserve1 *big.Int
}
